#!/bin/bash

MP3FS_EXTRA_ARGS="--gainmode=0"
. "${BASH_SOURCE%/*}/funcs.sh"

get_metadata() {
    python3 <<END
import mutagen
file = mutagen.File('$1')
tags = ['%s=%s' % (k, v) for k, v in file.tags.items() if k[0] == 'T' or k.startswith('UFID')]
print('\n'.join(sorted(tags)))
END
}

cmp -s - <(get_metadata "$DIRNAME/obama.mp3") <<END
TALB=US State of the Union 2011
TCON=Spoken
TCOP=Public Domain
TDRC=2011-01-25
TIT2=The Internet [excerpt]
TLEN=6000
TPE1=Barack Obama
TPOS=0/0
TRCK=1/1
TSSE=MP3FS
TXXX:MusicBrainz Album Artist Id=368fc319-4815-44f9-9933-40572f1b6844
TXXX:MusicBrainz Album Id=7663f268-ff12-4ed7-b4f6-4d1ad00c40bf
TXXX:MusicBrainz Album Release Country=US
TXXX:MusicBrainz Album Status=Bootleg
TXXX:MusicBrainz Album Type=Other
TXXX:MusicBrainz Artist Id=326cc352-ff9a-4f43-ab3d-d396ccbff3e7
TXXX:MusicBrainz Release Group Id=158e187b-0563-494a-a6d4-46d95e83ee29
TXXX:REPLAYGAIN_ALBUM_GAIN=+3.72 dB
TXXX:REPLAYGAIN_ALBUM_PEAK=0.35464478
TXXX:REPLAYGAIN_REFERENCE_LOUDNESS=89.0 dB
TXXX:REPLAYGAIN_TRACK_GAIN=+3.72 dB
TXXX:REPLAYGAIN_TRACK_PEAK=0.35464478
UFID:http://musicbrainz.org=UFID(owner='http://musicbrainz.org', data=b'a50f3899-fb64-43a1-a33c-f1d1687a98bb')
END

cmp -s - <(get_metadata "$DIRNAME/raven.mp3") <<END
TALB=The Raven
TCON=Speech
TDRC=2007
TIT2=the_raven
TLEN=21002
TPE1=Edgar Allen Poe
TRCK=01
TSSE=MP3FS
TXXX:MusicBrainz Album Artist Id=368fc319-4815-44f9-9933-40572f1b6844
TXXX:MusicBrainz Album Id=7663f268-ff12-4ed7-b4f6-4d1ad00c40bf
TXXX:MusicBrainz Album Release Country=US
TXXX:MusicBrainz Album Status=Bootleg
TXXX:MusicBrainz Album Type=Other
TXXX:MusicBrainz Artist Id=326cc352-ff9a-4f43-ab3d-d396ccbff3e7
TXXX:MusicBrainz Release Group Id=158e187b-0563-494a-a6d4-46d95e83ee29
TXXX:REPLAYGAIN_ALBUM_GAIN=+1.08 dB
TXXX:REPLAYGAIN_ALBUM_PEAK=0.58668917
TXXX:REPLAYGAIN_TRACK_GAIN=+1.08 dB
TXXX:REPLAYGAIN_TRACK_PEAK=0.58668917
UFID:http://musicbrainz.org=UFID(owner='http://musicbrainz.org', data=b'a50f3899-fb64-43a1-a33c-f1d1687a98bb')
END
